import 'package:flutter/material.dart';
import 'package:iconsax/iconsax.dart';
import '../../../core/widgets/policy_scaffold.dart';

class TermsConditionsScreen extends StatelessWidget {
  const TermsConditionsScreen({super.key});

  static const List<PolicySection> _sections = [
    PolicySection(
      heading: '1. General Overview & Scope',
      paragraph:
          'In accordance with the Information Technology Act, 2000 and applicable rules, this document is an electronic record generated by a computer system and does not require physical or digital signatures.',
      bullets: [
        'Platform Role: Drishti Fashions serves as an online e-commerce platform connecting buyers and independent brands/sellers. We curate a premium collection of fashion wear while commercial terms (pricing, delivery, warranties) are fulfilled independently.',
        'Personal Use Only: The Site is strictly for your personal, non-commercial use. Unauthorised commercial use, duplication, or resale of any product or content is prohibited.',
      ],
    ),
    PolicySection(
      heading: '2. User Accounts & Security',
      paragraph:
          'The Site is intended for use by adults. Any minor accessing the platform should do so under parental or guardian supervision.',
      bullets: [
        'Account Responsibility: You are responsible for maintaining the confidentiality of your account credentials, password, and restricting access to your devices. All activities under your account are your sole responsibility.',
        'Termination: We reserve the right to refuse service, terminate accounts, or cancel orders at our sole discretion if these Terms are violated.',
      ],
    ),
    PolicySection(
      heading: '3. Orders, Pricing & Payments',
      bullets: [
        'Order Placement: Placing an order constitutes an offer to buy. Drishti Fashions or our sellers retain the right to accept or cancel any order (including orders exceeding typical individual consumption limits) at our discretion.',
        'Pricing Accuracy: While we strive for accuracy, pricing or informational errors may occur. If a product is listed at an incorrect price, we reserve the right to cancel the order and issue a full refund.',
        'Payment Modes: Payments can be made via Credit Cards, Debit Cards, Net Banking, Wallets, UPI, Cash on Delivery (COD), and gift cards.',
      ],
    ),
    PolicySection(
      heading: '4. Intellectual Property Rights',
      paragraph:
          'All content on this Site—including the Drishti Fashions name, logos, text, designs, graphics, icons, images, audio clips, and software—is the exclusive property of DRISTI DHIMAHI VYAPAAR PRIVATE LIMITED or its licensors and is protected by Indian copyright and trademark laws.',
      bullets: [
        'Restrictions: You may not copy, reproduce, distribute, republish, download, or modify any content from the Site without explicit written permission, except for your personal, non-commercial viewing.',
      ],
    ),
    PolicySection(
      heading: '5. Limitation of Liability & Disclaimers',
      paragraph:
          'The Site and its contents are provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, either express or implied. Drishti Fashions, its directors, employees, or affiliates shall not be liable for any indirect, incidental, punitive, or consequential damages arising from your use of the Site, product delays, or third-party actions.',
    ),
    PolicySection(
      heading: '6. Governing Law & Dispute Resolution',
      bullets: [
        'Jurisdiction: These Terms & Conditions shall be governed by and construed in accordance with the laws of India. Any legal proceedings shall be subject to the exclusive jurisdiction of the courts in Kolkata, West Bengal.',
        'Arbitration: Any disputes arising out of these Terms shall be referred to an independent arbitrator appointed mutually, in accordance with the Arbitration and Conciliation Act, 1996, with the seat of arbitration in Kolkata.',
      ],
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return const PolicyScaffold(
      title: 'Terms & Conditions',
      intro:
          'Welcome to Drishti Fashions. By accessing, browsing, or shopping on our platform, you acknowledge and agree to be bound by these Terms & Conditions, along with our Privacy Policy and Shipping & Return Policies (collectively, the "Policies").',
      sections: _sections,
      contactHeading: 'Contact Information',
      contactIntro:
          'If you have any questions or concerns regarding these Terms & Conditions, please reach out to our Customer Service Desk:',
      contactDetails: [
        ContactDetail(label: 'Name', value: 'Mr. Prakash — Operations Head', icon: Iconsax.user),
        ContactDetail(label: 'Email', value: 'info@drishtifashions.com', icon: Iconsax.sms),
        ContactDetail(label: 'Phone', value: '+91 6290486090 (Mon-Sat, 10 AM to 7 PM)', icon: Iconsax.call),
      ],
    );
  }
}